[profile.default]
via-ir = true
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.22"
[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
